import React from 'react';
import Head from 'next/head';
import grid from '../public/assets/grid.jpg';
import single_player from '../public/assets/single_player.gif';
import game from '../public/assets/game.gif';
import ImageExplainer from '../components/ImageExplainer';
import styles from '../styles/Rules.module.css';

export default function rules() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Rules.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}
          style={{maxWidth: '70%'}}
        >
          How to Play
        </h1>
        <div className={styles.display_rules}>
          <h2>How it works.</h2>
          <p className={styles.description}>
            The universe of the Game of Life is an infinite, two-dimensional orthogonal grid of square cells, each of which is in one of two possible states, live or dead (or populated and unpopulated, respectively). Every cell interacts with its eight neighbours, which are the cells that are horizontally, vertically, or diagonally adjacent. At each step in time, the following transitions occur:
          </p>
          <div className={styles.data_grid}>
            <p>
            <div className={styles.rules_intro}>
            <ol style={{fontSize: 'larger'}}>
              <li className={styles.list_item}>
                Any live cell with fewer than two live neighbours dies, as if by underpopulation.
              </li>
              <li className={styles.list_item}>
                Any live cell with two or three live neighbours lives on to the next generation.
              </li>
              <li className={styles.list_item}>
              Any live cell with more than three live neighbours dies, as if by overpopulation.
              </li>
              <li className={styles.list_item}>
              Any dead cell with exactly three live neighbours becomes a live cell, as if by reproduction.
              </li>
            </ol>
            <br />
            <p>This will play on for multiple generations where each generation is influenced by the end results of the last generation.</p>
            </div>
            </p>
         
            <ImageExplainer 
              img={grid} 
              title={'game board with one cell'} 
              tagline={'the board '} 
              link={''}
            />
          </div>

          <div className={styles.rules_intro}>
            <div className={styles.data_grid}>
            <ImageExplainer 
                img={single_player} 
                title={''} 
                tagline={''} 
                link={''}/>
              <p style={{fontSize: 'larger'}}> 
                These rules, which compare the behavior of the automaton to real life, can be condensed into the following:
                <br />
                <br />
                <ol>
                  <li className={styles.list_item}>
                  Any live cell with two or three live neighbours survives.
                  </li>
                  <li className={styles.list_item}>
                  Any dead cell with three live neighbours becomes a live cell.
                  </li>
                  <li className={styles.list_item}> 
                  All other live cells die in the next generation. Similarly, all other dead cells stay dead.
                  </li>
                </ol>
                <br />
                <br />
                The initial pattern constitutes the seed of the system. The first generation is created by applying the above rules simultaneously to every cell in the seed, live or dead; births and deaths occur simultaneously, and the discrete moment at which this happens is sometimes called a tick.
                <br />
                <br />
                 Each generation is a pure function of the preceding one. The rules continue to be applied repeatedly to create further generations.
              </p>
               
            </div>
          </div>
          <hr style={{
            marginTop: '2em',
            marginBottom: '2em',
            width: '70vw',
            backgroundColor: '#0070f3'
          }}/>
          <div className={styles.rules_intro}>
            <h2>Our Twist and the rules of the game.</h2>
            <p className={styles.description}>
              To introduce more people to this game we are adding a multiplayer feature, allowing 2 players to compete against each other. Each player will buy an initial amount of cells, the payment will be escrowed until the game is over, the winner will receive the full escrowed amount.
            </p>
          </div>

          <div className={styles.data_grid}>
            <ImageExplainer 
                img={game} 
                title={''} 
                tagline={''} 
                link={''}/>
              <p style={{fontSize: 'larger'}}> 
                Two players will play against each other to win a prize pool which is equal to the total bet by both players, each player will purchase 15 cells to play initially.
                <br />
                <br />
                <ol>
                  <li className={styles.list_item}>
                  Player 1 creates the game room and places their 15 cells on the board
                  </li>
                  <li className={styles.list_item}>
                  Player 2 joins the game room and places their 15 cells on the board
                  </li>
                  <li className={styles.list_item}> 
                  The game will run until theres only 1 player standing, or the game reaches 500 generations.&apos;
                  </li>
                  <li className={styles.list_item}> 
                  The player with the most amount of cells remaining by the end will win the total pooled bets.
                  </li>
                </ol>
                <br />
                <br />
                The results will be minted as an NFT and put on a leaderboard for people to view, we hope to contribute to the body of data for researchers to learn from.
                <br />
                <br />
                Youre all ready to start the game, good luck!
                &apos;
              </p>
               
            </div>
        </div>
       
      </main>
    </div>
  )
}
